version: '3.8'

services:
  xrp-bot:
    container_name: xrp-grid-bot
    build: .
    restart: unless-stopped

    environment:
      - TZ=Europe/London
      - PUID=${PUID}
      - PGID=${PGID}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY}
      - PUSHOVER_API_TOKEN=${PUSHOVER_API_TOKEN}
      - SYMBOL=${SYMBOL}
      - BASE_CURRENCY=${BASE_CURRENCY}
      - QUOTE_CURRENCY=${QUOTE_CURRENCY}
      - TRADE_AMOUNT=${TRADE_AMOUNT}
      - DRY_RUN=${DRY_RUN}
      - LOG_LEVEL=${LOG_LEVEL}

    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      # - ./data:/app/data         # (future: historique de marché)
      # - ./backups:/app/backups   # (future: snapshots de config, wallets, etc.)
      # - ./scripts:/app/scripts   # (si scripts manuels ou cron internes)
    
    working_dir: /app
