version: '3'

services:
  xrp_trading_bot:
    build: .
    container_name: xrp_trading_bot
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    environment:
      - TZ=Europe/Paris
    command: python3 src/main.py
    # Uncomment the following lines if you want to use a specific user ID and group ID
    # user: "1000:1000"
