version: '3'

services:
  xrp_trading_bot:
    image: python:3.9-slim
    container_name: xrp_trading_bot
    restart: always
    volumes:
      - ./xrp_trading_bot.py:/app/xrp_trading_bot.py
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    command: >
      bash -c "pip install --no-cache-dir krakenex pykrakenapi pandas numpy requests &&
              python /app/xrp_trading_bot.py --enable_telegram"
    environment:
      - TZ=Europe/London
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/trading_log.txt') else 1)"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 2m
    labels:
      - "com.synology.dsm.auto-restart=true"
